# Generated by Django 2.2 on 2019-05-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_friend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='cuser',
            new_name='current_user',
        ),
    ]
